apiVersion: 3
dataDisplay:
  textFormats:
    text-orig-full: 
      method: layoutRich
      style:  normal
interfaceDefaults: {}
provenanceSpec:
  corpus: vulgate
  version: '0.1'
typeDisplay:
  book:
    featuresBare: author
  verse:
    features: language
    label: '{number}'
    template: '{number}'
    verselike: true
  word:
    features: lexeme
